import { create } from "zustand";

export const flowerPresets = [
  "Daisy",
  "Cosmos",
  "Sunset",
  "Poppy",
  "Coneflower",
  "Dahlia",
  "Rose",
  "Sunflower",
  "Peony",
  "Lotus",
  "Anemone",
  "Zinnia",
  "Tulip",
  "Iris",
  "Lily",
  "Orchid",
  "Carnation",
  "Cherry Blossom",
  "Magnolia",
  "Camellia",
  "Chrysanthemum",
  "Daffodil",
  "Hibiscus",
  "Marigold",
  "Pansy",
  "Gardenia",
  "Ranunculus",
  "Gerbera",
  "Bluebell",
  "Protea",
  "Water Lily",
  "Morning Glory",
  "Calla Lily",
  "Forget-me-not",
  "Aster",
  "Clematis",
  "Hellebore",
  "Crocus",
  "Amaryllis",
  "Primrose",
  "Plumeria",
  "Poinsettia",
] as const;

export type FlowerPreset = (typeof flowerPresets)[number];

export type FlowerSettings = {
  renderMode: "color" | "line" | "photo";
  preset: FlowerPreset;
  petalCount: number;
  petalLength: number;
  petalWidth: number;
  petalCurl: number;
  petalWaviness: number;
  petalThickness: number;
  petalFold: number;
  petalTwist: number;
  petalRuffle: number;
  petalNotch: number;
  petalVeinStrength: number;
  petalBaseWidth: number;
  petalAge: number;
  petalSpots: number;
  petalGuideStrength: number;
  bloom: number;
  variation: number;
  petalColor: string;
  petalTipColor: string;
  centerColor: string;
  centerDensity: number;
  centerSize: number;
  centerProfile: number;
  centerFloretSize: number;
  centerSpread: number;
  centerStamenLength: number;
  centerAntherSize: number;
  centerStigmaSize: number;
  stemColor: string;
  backgroundColor: string;
  stemCurve: number;
  stemHeight: number;
  stemThickness: number;
  stemTaper: number;
  stemNodeCount: number;
  stemHairDensity: number;
  leafDensity: number;
  leafLength: number;
  leafWidth: number;
  leafCurl: number;
  leafSerration: number;
  leafVeinDensity: number;
  leafDroop: number;
  bloomTilt: number;
  bloomTurn: number;
  lightIntensity: number;
  seed: number;
  grid: boolean;
};

export type FlowerState = FlowerSettings & {
  panelOpen: boolean;
  rightPanelOpen: boolean;
  set: <K extends keyof FlowerSettings>(
    key: K,
    value: FlowerSettings[K],
  ) => void;
  applyPreset: (preset: FlowerPreset) => void;
  randomize: () => void;
  togglePanel: () => void;
  toggleRightPanel: () => void;
  loadSettings: (settings: FlowerSettings) => void;
};

const presets: Record<FlowerPreset, Partial<FlowerSettings>> = {
  Daisy: {
    petalCount: 20,
    petalLength: 1.45,
    petalWidth: 0.42,
    petalCurl: 0.18,
    bloom: 0.9,
    variation: 0.12,
    petalColor: "#f7efe7",
    petalTipColor: "#ead9d1",
    centerColor: "#d79c32",
    stemColor: "#42643d",
    backgroundColor: "#ffffff",
  },
  Cosmos: {
    petalCount: 12,
    petalLength: 1.65,
    petalWidth: 0.62,
    petalCurl: 0.28,
    bloom: 0.82,
    variation: 0.2,
    petalColor: "#d47a9a",
    petalTipColor: "#f0b4c2",
    centerColor: "#cf9b38",
    stemColor: "#355a39",
    backgroundColor: "#ffffff",
  },
  Sunset: {
    petalCount: 16,
    petalLength: 1.5,
    petalWidth: 0.52,
    petalCurl: 0.42,
    bloom: 0.74,
    variation: 0.16,
    petalColor: "#d95f45",
    petalTipColor: "#efaa76",
    centerColor: "#6f3428",
    stemColor: "#3e5632",
    backgroundColor: "#ffffff",
  },
  Poppy: {
    petalCount: 6,
    petalLength: 1.55,
    petalWidth: 0.95,
    petalCurl: 0.2,
    bloom: 0.86,
    variation: 0.3,
    petalColor: "#c9342f",
    petalTipColor: "#f06a55",
    centerColor: "#2b211e",
    stemColor: "#4a693f",
    backgroundColor: "#ffffff",
  },
  Coneflower: {
    petalCount: 18,
    petalLength: 1.7,
    petalWidth: 0.4,
    petalCurl: 0.18,
    bloom: 0.64,
    variation: 0.18,
    petalColor: "#b85f87",
    petalTipColor: "#dd91ad",
    centerColor: "#8b512d",
    stemColor: "#3f633a",
    backgroundColor: "#ffffff",
  },
  Dahlia: {
    petalCount: 22,
    petalLength: 1.35,
    petalWidth: 0.38,
    petalCurl: 0.5,
    bloom: 0.7,
    variation: 0.13,
    petalColor: "#a82f58",
    petalTipColor: "#e8829e",
    centerColor: "#7f2945",
    stemColor: "#365c39",
    backgroundColor: "#ffffff",
  },
  Rose: {
    petalCount: 18,
    petalLength: 1.25,
    petalWidth: 0.68,
    petalCurl: 0.62,
    bloom: 0.58,
    variation: 0.12,
    petalColor: "#b93657",
    petalTipColor: "#ef8da0",
    centerColor: "#7d283e",
    stemColor: "#315d38",
    backgroundColor: "#ffffff",
  },
  Sunflower: {
    petalCount: 28,
    petalLength: 1.65,
    petalWidth: 0.4,
    petalCurl: 0.16,
    bloom: 0.9,
    variation: 0.14,
    petalColor: "#e7a51e",
    petalTipColor: "#f6cb43",
    centerColor: "#55351f",
    stemColor: "#3f6335",
    backgroundColor: "#ffffff",
  },
  Peony: {
    petalCount: 20,
    petalLength: 1.38,
    petalWidth: 0.74,
    petalCurl: 0.46,
    bloom: 0.66,
    variation: 0.22,
    petalColor: "#dc829a",
    petalTipColor: "#f4bdc8",
    centerColor: "#d29b38",
    stemColor: "#365f3d",
    backgroundColor: "#ffffff",
  },
  Lotus: {
    petalCount: 16,
    petalLength: 1.55,
    petalWidth: 0.7,
    petalCurl: 0.32,
    bloom: 0.62,
    variation: 0.09,
    petalColor: "#e39bad",
    petalTipColor: "#f5d5dc",
    centerColor: "#d5aa3d",
    stemColor: "#48715b",
    backgroundColor: "#ffffff",
  },
  Anemone: {
    petalCount: 9,
    petalLength: 1.5,
    petalWidth: 0.78,
    petalCurl: 0.2,
    bloom: 0.88,
    variation: 0.18,
    petalColor: "#6f55a4",
    petalTipColor: "#b9a8da",
    centerColor: "#24222d",
    stemColor: "#41633e",
    backgroundColor: "#ffffff",
  },
  Zinnia: {
    petalCount: 22,
    petalLength: 1.28,
    petalWidth: 0.42,
    petalCurl: 0.38,
    bloom: 0.72,
    variation: 0.12,
    petalColor: "#df5b4f",
    petalTipColor: "#f49a7d",
    centerColor: "#b56b2b",
    stemColor: "#3b6139",
    backgroundColor: "#ffffff",
  },
  Tulip: {
    petalCount: 6,
    petalLength: 1.72,
    petalWidth: 0.82,
    petalCurl: 0.2,
    bloom: 0.54,
    variation: 0.08,
    petalColor: "#c93f58",
    petalTipColor: "#ef8792",
    centerColor: "#403629",
    stemColor: "#3f703f",
    backgroundColor: "#ffffff",
  },
  Iris: {
    petalCount: 6,
    petalLength: 1.72,
    petalWidth: 0.78,
    petalCurl: 0.48,
    bloom: 0.68,
    variation: 0.12,
    petalColor: "#6551a2",
    petalTipColor: "#a794d5",
    centerColor: "#e2ad3d",
    stemColor: "#4a7048",
    backgroundColor: "#ffffff",
  },
  Lily: {
    petalCount: 6,
    petalLength: 2.05,
    petalWidth: 0.65,
    petalCurl: 0.36,
    bloom: 0.86,
    variation: 0.09,
    petalColor: "#f0d8d4",
    petalTipColor: "#d87582",
    centerColor: "#b6a84a",
    stemColor: "#416c3d",
    backgroundColor: "#ffffff",
  },
  Orchid: {
    petalCount: 5,
    petalLength: 1.62,
    petalWidth: 0.82,
    petalCurl: 0.3,
    bloom: 0.8,
    variation: 0.08,
    petalColor: "#ead9ed",
    petalTipColor: "#ae5a9d",
    centerColor: "#d58b42",
    stemColor: "#47704a",
    backgroundColor: "#ffffff",
  },
  Carnation: {
    petalCount: 28,
    petalLength: 1.2,
    petalWidth: 0.68,
    petalCurl: 0.62,
    bloom: 0.7,
    variation: 0.22,
    petalColor: "#d85f72",
    petalTipColor: "#f3a3ad",
    centerColor: "#b75065",
    stemColor: "#527257",
    backgroundColor: "#ffffff",
  },
  "Cherry Blossom": {
    petalCount: 5,
    petalLength: 1.35,
    petalWidth: 0.9,
    petalCurl: 0.16,
    bloom: 0.92,
    variation: 0.1,
    petalColor: "#f0c5cf",
    petalTipColor: "#fff0f2",
    centerColor: "#c58b3c",
    stemColor: "#536444",
    backgroundColor: "#ffffff",
  },
  Magnolia: {
    petalCount: 9,
    petalLength: 1.78,
    petalWidth: 0.88,
    petalCurl: 0.22,
    bloom: 0.72,
    variation: 0.07,
    petalColor: "#eee4df",
    petalTipColor: "#d9a8ae",
    centerColor: "#b59a4a",
    stemColor: "#506644",
    backgroundColor: "#ffffff",
  },
  Camellia: {
    petalCount: 24,
    petalLength: 1.3,
    petalWidth: 0.72,
    petalCurl: 0.4,
    bloom: 0.64,
    variation: 0.08,
    petalColor: "#c8324f",
    petalTipColor: "#ea7887",
    centerColor: "#d4aa3e",
    stemColor: "#315b38",
    backgroundColor: "#ffffff",
  },
  Chrysanthemum: {
    petalCount: 32,
    petalLength: 1.45,
    petalWidth: 0.3,
    petalCurl: 0.72,
    bloom: 0.62,
    variation: 0.16,
    petalColor: "#d69a35",
    petalTipColor: "#f0c663",
    centerColor: "#a76d28",
    stemColor: "#46643b",
    backgroundColor: "#ffffff",
  },
  Daffodil: {
    petalCount: 6,
    petalLength: 1.62,
    petalWidth: 0.72,
    petalCurl: 0.18,
    bloom: 0.88,
    variation: 0.07,
    petalColor: "#f1d64e",
    petalTipColor: "#fff09a",
    centerColor: "#e69824",
    stemColor: "#52713d",
    backgroundColor: "#ffffff",
  },
  Hibiscus: {
    petalCount: 5,
    petalLength: 1.82,
    petalWidth: 1.05,
    petalCurl: 0.3,
    bloom: 0.9,
    variation: 0.11,
    petalColor: "#d83c57",
    petalTipColor: "#f28391",
    centerColor: "#8c2437",
    stemColor: "#3c683b",
    backgroundColor: "#ffffff",
  },
  Marigold: {
    petalCount: 30,
    petalLength: 1.16,
    petalWidth: 0.52,
    petalCurl: 0.56,
    bloom: 0.7,
    variation: 0.17,
    petalColor: "#e88718",
    petalTipColor: "#f7bd31",
    centerColor: "#a95e18",
    stemColor: "#3f6537",
    backgroundColor: "#ffffff",
  },
  Pansy: {
    petalCount: 5,
    petalLength: 1.42,
    petalWidth: 1.08,
    petalCurl: 0.14,
    bloom: 0.94,
    variation: 0.06,
    petalColor: "#7253a4",
    petalTipColor: "#c5a8df",
    centerColor: "#e0b43e",
    stemColor: "#41633c",
    backgroundColor: "#ffffff",
  },
  Gardenia: {
    petalCount: 20,
    petalLength: 1.34,
    petalWidth: 0.82,
    petalCurl: 0.5,
    bloom: 0.62,
    variation: 0.08,
    petalColor: "#f1eee4",
    petalTipColor: "#fffdf5",
    centerColor: "#d7c37a",
    stemColor: "#315b38",
    backgroundColor: "#ffffff",
  },
  Ranunculus: {
    petalCount: 30,
    petalLength: 1.26,
    petalWidth: 0.72,
    petalCurl: 0.44,
    bloom: 0.58,
    variation: 0.07,
    petalColor: "#e57466",
    petalTipColor: "#f6b3a3",
    centerColor: "#b96053",
    stemColor: "#41663d",
    backgroundColor: "#ffffff",
  },
  Gerbera: {
    petalCount: 30,
    petalLength: 1.72,
    petalWidth: 0.35,
    petalCurl: 0.12,
    bloom: 0.94,
    variation: 0.1,
    petalColor: "#e0525f",
    petalTipColor: "#f59691",
    centerColor: "#49352a",
    stemColor: "#41613a",
    backgroundColor: "#ffffff",
  },
  Bluebell: {
    petalCount: 6,
    petalLength: 1.48,
    petalWidth: 0.6,
    petalCurl: 0.68,
    bloom: 0.38,
    variation: 0.08,
    petalColor: "#536bbb",
    petalTipColor: "#91a7e0",
    centerColor: "#d8cf92",
    stemColor: "#416b42",
    backgroundColor: "#ffffff",
  },
  Protea: {
    petalCount: 28,
    petalLength: 1.55,
    petalWidth: 0.32,
    petalCurl: 0.18,
    bloom: 0.46,
    variation: 0.12,
    petalColor: "#b9586d",
    petalTipColor: "#e69aaa",
    centerColor: "#865044",
    stemColor: "#466348",
    backgroundColor: "#ffffff",
  },
  "Water Lily": {
    petalCount: 22,
    petalLength: 1.62,
    petalWidth: 0.58,
    petalCurl: 0.22,
    bloom: 0.78,
    variation: 0.08,
    petalColor: "#eee4ed",
    petalTipColor: "#c882aa",
    centerColor: "#d6a932",
    stemColor: "#47705a",
    backgroundColor: "#ffffff",
  },
  "Morning Glory": {
    petalCount: 5,
    petalLength: 1.68,
    petalWidth: 1.12,
    petalCurl: 0.14,
    bloom: 0.72,
    variation: 0.05,
    petalColor: "#536fb4",
    petalTipColor: "#a8bce4",
    centerColor: "#f0e5bd",
    stemColor: "#456842",
    backgroundColor: "#ffffff",
  },
  "Calla Lily": {
    petalCount: 1,
    petalLength: 2.15,
    petalWidth: 1.18,
    petalCurl: 0.62,
    bloom: 0.48,
    variation: 0.03,
    petalColor: "#eeeae0",
    petalTipColor: "#fffdf5",
    centerColor: "#d8b53f",
    stemColor: "#477245",
    backgroundColor: "#ffffff",
  },
  "Forget-me-not": {
    petalCount: 5,
    petalLength: 1.1,
    petalWidth: 0.92,
    petalCurl: 0.08,
    bloom: 0.96,
    variation: 0.08,
    petalColor: "#668ec9",
    petalTipColor: "#a9c8e8",
    centerColor: "#e5bb38",
    stemColor: "#456742",
    backgroundColor: "#ffffff",
  },
  Aster: {
    petalCount: 30,
    petalLength: 1.62,
    petalWidth: 0.28,
    petalCurl: 0.12,
    bloom: 0.94,
    variation: 0.11,
    petalColor: "#765ca8",
    petalTipColor: "#ae9bd2",
    centerColor: "#d5a33a",
    stemColor: "#42633d",
    backgroundColor: "#ffffff",
  },
  Clematis: {
    petalCount: 8,
    petalLength: 1.72,
    petalWidth: 0.72,
    petalCurl: 0.16,
    bloom: 0.92,
    variation: 0.09,
    petalColor: "#7957a0",
    petalTipColor: "#b59bd0",
    centerColor: "#d6c6a2",
    stemColor: "#496448",
    backgroundColor: "#ffffff",
  },
  Hellebore: {
    petalCount: 5,
    petalLength: 1.55,
    petalWidth: 0.94,
    petalCurl: 0.18,
    bloom: 0.82,
    variation: 0.1,
    petalColor: "#c8bdcf",
    petalTipColor: "#e7dde8",
    centerColor: "#b9a94c",
    stemColor: "#455f42",
    backgroundColor: "#ffffff",
  },
  Crocus: {
    petalCount: 6,
    petalLength: 1.72,
    petalWidth: 0.72,
    petalCurl: 0.16,
    bloom: 0.52,
    variation: 0.06,
    petalColor: "#7756a6",
    petalTipColor: "#ad98d2",
    centerColor: "#e3a936",
    stemColor: "#527145",
    backgroundColor: "#ffffff",
  },
  Amaryllis: {
    petalCount: 6,
    petalLength: 1.95,
    petalWidth: 0.82,
    petalCurl: 0.28,
    bloom: 0.84,
    variation: 0.08,
    petalColor: "#c93f4b",
    petalTipColor: "#ee8d8d",
    centerColor: "#d4bd73",
    stemColor: "#497143",
    backgroundColor: "#ffffff",
  },
  Primrose: {
    petalCount: 5,
    petalLength: 1.3,
    petalWidth: 0.96,
    petalCurl: 0.08,
    bloom: 0.95,
    variation: 0.07,
    petalColor: "#e8cf58",
    petalTipColor: "#f8eca1",
    centerColor: "#d18c2e",
    stemColor: "#46643e",
    backgroundColor: "#ffffff",
  },
  Plumeria: {
    petalCount: 5,
    petalLength: 1.62,
    petalWidth: 0.9,
    petalCurl: 0.22,
    bloom: 0.86,
    variation: 0.04,
    petalColor: "#eee9df",
    petalTipColor: "#d9869b",
    centerColor: "#e4b33b",
    stemColor: "#4b6744",
    backgroundColor: "#ffffff",
  },
  Poinsettia: {
    petalCount: 12,
    petalLength: 1.72,
    petalWidth: 0.58,
    petalCurl: 0.14,
    bloom: 0.92,
    variation: 0.12,
    petalColor: "#b92f3c",
    petalTipColor: "#dc6870",
    centerColor: "#b5a039",
    stemColor: "#3f613c",
    backgroundColor: "#ffffff",
  },
};

export const useFlowerStore = create<FlowerState>((set) => ({
  renderMode: "color",
  preset: "Cosmos",
  petalCount: 12,
  petalLength: 1.65,
  petalWidth: 0.62,
  petalCurl: 0.28,
  petalWaviness: 0.18,
  petalThickness: 1,
  petalFold: 0.5,
  petalTwist: 0.5,
  petalRuffle: 1,
  petalNotch: 1,
  petalVeinStrength: 1,
  petalBaseWidth: 1,
  petalAge: 0,
  petalSpots: 0,
  petalGuideStrength: 0.12,
  bloom: 0.82,
  variation: 0.2,
  petalColor: "#d47a9a",
  petalTipColor: "#f0b4c2",
  centerColor: "#cf9b38",
  centerDensity: 1,
  centerSize: 1,
  centerProfile: 1,
  centerFloretSize: 1,
  centerSpread: 1,
  centerStamenLength: 1,
  centerAntherSize: 1,
  centerStigmaSize: 1,
  stemColor: "#355a39",
  backgroundColor: "#ffffff",
  stemCurve: 0.35,
  stemHeight: 1,
  stemThickness: 1,
  stemTaper: 0.38,
  stemNodeCount: 2,
  stemHairDensity: 1,
  leafDensity: 1,
  leafLength: 1,
  leafWidth: 1,
  leafCurl: 0.35,
  leafSerration: 1,
  leafVeinDensity: 1,
  leafDroop: 0.25,
  bloomTilt: 0,
  bloomTurn: 0,
  lightIntensity: 1.4,
  seed: 42,
  grid: false,
  panelOpen: true,
  rightPanelOpen: true,
  set: (key, value) => set({ [key]: value }),
  applyPreset: (preset) =>
    set({
      preset,
      ...presets[preset],
      seed: Math.floor(Math.random() * 10000),
    }),
  randomize: () =>
    set((state) => ({
      seed: Math.floor(Math.random() * 100000),
      petalCount: Math.max(
        1,
        Math.min(32, state.petalCount + Math.floor(Math.random() * 7) - 3),
      ),
      petalCurl: Math.max(
        0,
        Math.min(1, state.petalCurl + Math.random() * 0.3 - 0.15),
      ),
      variation: Math.max(
        0.04,
        Math.min(0.45, state.variation + Math.random() * 0.15 - 0.05),
      ),
    })),
  togglePanel: () => set((state) => ({ panelOpen: !state.panelOpen })),
  toggleRightPanel: () =>
    set((state) => ({ rightPanelOpen: !state.rightPanelOpen })),
  loadSettings: (settings) => set(settings),
}));
