import type { FlowerPreset, FlowerSettings } from "./flower-store";
import type { FlowerSpecies } from "./flower-species";

export type HeroFlowerPreset = Extract<
  FlowerPreset,
  "Rose" | "Poppy" | "Lily" | "Sunflower" | "Orchid" | "Lotus"
>;

type HeroFlowerProfile = {
  label: string;
  referenceViews: readonly string[];
  traits: readonly string[];
  referenceChecks: readonly string[];
  store: Partial<FlowerSettings>;
  structure: FlowerSpecies;
};

export const heroFlowerProfiles: Record<HeroFlowerPreset, HeroFlowerProfile> = {
  Rose: {
    label: "Rose",
    referenceViews: ["front", "center", "calyx", "foliage", "stem"],
    traits: [
      "Open, shallow bloom with broad, slightly wavy petals",
      "Visible yellow stamen ring around a pale center",
      "Glossy, heavily veined foliage around the flower",
      "A thorny, woody stem and compact calyx keep the bloom believable",
    ],
    referenceChecks: [
      "Front view should read wide and open rather than tightly spiraled.",
      "Center should stay readable as a pale boss with a yellow ring.",
      "Leaves should feel glossy and strongly textured.",
      "The bloom should stay shallow in profile with a compact calyx.",
      "The stem should read woody and slightly rough, not smooth or succulent.",
    ],
    store: {
      petalCount: 14,
      petalLength: 1.28,
      petalWidth: 0.76,
      petalCurl: 0.34,
      petalWaviness: 0.16,
      petalThickness: 0.92,
      petalFold: 0.24,
      petalTwist: 0.18,
      petalRuffle: 0.44,
      petalNotch: 0.06,
      petalVeinStrength: 1.04,
      petalBaseWidth: 1.12,
      petalAge: 0.08,
      petalSpots: 0,
      petalGuideStrength: 0.06,
      petalAsymmetry: 0.04,
      petalTranslucency: 0.12,
      petalEdgeWear: 0.04,
      petalSheen: 0.44,
      bloom: 0.74,
      variation: 0.12,
      petalColor: "#be4a76",
      petalTipColor: "#dc91a2",
      centerColor: "#f0e0c8",
      stemColor: "#315c39",
      backgroundColor: "#ffffff",
      centerDensity: 1.02,
      centerSize: 0.78,
      centerProfile: 0.84,
      centerFloretSize: 0.92,
      centerSpread: 0.82,
      centerStamenLength: 0.9,
      centerAntherSize: 0.9,
      centerStigmaSize: 0.84,
      sepalSize: 1.08,
      sepalSpread: 0.18,
      stemCurve: 0.16,
      stemHeight: 1.02,
      stemThickness: 0.84,
      stemTaper: 0.26,
      stemNodeCount: 3,
      stemHairDensity: 0.24,
      leafDensity: 1.12,
      leafLength: 1,
      leafWidth: 1.12,
      leafCurl: 0.12,
      leafSerration: 1.22,
      leafVeinDensity: 1.18,
      leafDroop: 0.08,
      leafAsymmetry: 0.06,
      leafAge: 0.06,
      bloomTilt: -0.04,
      bloomTurn: -0.1,
      lightIntensity: 1.28,
    },
    structure: {
      layers: [
        { count: 1, length: 1, width: 1, lift: -0.04, offset: 0 },
        { count: 0.84, length: 0.82, width: 0.94, lift: 0.16, offset: 0.5 },
        { count: 0.64, length: 0.64, width: 0.86, lift: 0.31, offset: 0 },
        { count: 0.44, length: 0.48, width: 0.76, lift: 0.46, offset: 0.5 },
        { count: 0.28, length: 0.34, width: 0.66, lift: 0.58, offset: 0 },
      ],
      notch: 0.02,
      profile: 0.48,
      centerRadius: 0.12,
      florets: 30,
      sepals: 5,
      leafWidth: 0.36,
      centerHeight: 0.1,
      floretAccent: "#d48776",
      stamenCount: 10,
      stigmaLobes: 5,
      filamentColor: "#c88963",
      antherColor: "#75402f",
      stigmaColor: "#9d594f",
      pollenColor: "#d7a23d",
      styleLength: 0.72,
      ovaryPosition: "superior",
      ovaryScale: 0.86,
      calyxForm: "cupped",
      sepalLength: 0.82,
      edgeRuffle: 0.075,
      baseDarkening: 0.68,
      petalOutline: "obovate",
      longitudinalCurve: 0.32,
      lateralCup: 1.35,
      petalArrangement: "phyllotactic",
      receptacleRadius: 0.1,
      innerCompression: 0.72,
      overlapJitter: 0.38,
      leafShape: "ovate",
      leafSerration: 0.13,
      leafPairs: 2,
      stemEccentricity: 0.12,
      stemRibbing: 0.08,
    },
  },
  Poppy: {
    label: "Poppy",
    referenceViews: ["front", "center", "side", "habit", "bud"],
    traits: [
      "Papery, translucent petals with a broad flat opening",
      "Dark center with a dense stamen halo",
      "Loose, wind-blown form with a bright red face",
      "Bud and stem references keep the flower from feeling over-open",
    ],
    referenceChecks: [
      "Front should read as a flat saucer with thin petal edges.",
      "Center should be almost black against the red petals.",
      "Petals need visible translucency and crinkled texture.",
      "The habit view should feel sparse and wiry, not full-bodied.",
      "The bud should stay tight and slightly drooping on a thin stem.",
    ],
    store: {
      petalCount: 4,
      petalLength: 1.62,
      petalWidth: 1.06,
      petalCurl: 0.1,
      petalWaviness: 0.26,
      petalThickness: 0.48,
      petalFold: 0.04,
      petalTwist: 0.04,
      petalRuffle: 1.28,
      petalNotch: 0.14,
      petalVeinStrength: 0.82,
      petalBaseWidth: 1.22,
      petalAge: 0.08,
      petalSpots: 0.04,
      petalGuideStrength: 0.04,
      petalAsymmetry: 0.1,
      petalTranslucency: 0.68,
      petalEdgeWear: 0.16,
      petalSheen: 0.08,
      bloom: 0.9,
      variation: 0.24,
      petalColor: "#d33731",
      petalTipColor: "#ef7a63",
      centerColor: "#1c1613",
      stemColor: "#4c6a40",
      backgroundColor: "#ffffff",
      centerDensity: 1.02,
      centerSize: 0.7,
      centerProfile: 0.82,
      centerFloretSize: 0.9,
      centerSpread: 0.9,
      centerStamenLength: 1.18,
      centerAntherSize: 1,
      centerStigmaSize: 1.08,
      sepalSize: 0.78,
      sepalSpread: 0.12,
      stemCurve: 0.12,
      stemHeight: 1.05,
      stemThickness: 0.72,
      stemTaper: 0.24,
      stemNodeCount: 1,
      stemHairDensity: 0.5,
      leafDensity: 1.16,
      leafLength: 1.1,
      leafWidth: 0.76,
      leafCurl: 0.14,
      leafSerration: 1.34,
      leafVeinDensity: 1.05,
      leafDroop: 0.18,
      leafAsymmetry: 0.1,
      leafAge: 0.04,
      bloomTilt: -0.08,
      bloomTurn: 0.08,
      lightIntensity: 1.28,
    },
    structure: {
      layers: [
        { count: 1, length: 1, width: 1.15, lift: -0.04, offset: 0 },
        { count: 0.7, length: 0.86, width: 1.08, lift: 0.08, offset: 0.5 },
      ],
      notch: 0.045,
      profile: 0.34,
      centerRadius: 0.28,
      florets: 110,
      sepals: 3,
      leafWidth: 0.27,
      centerHeight: 0.18,
      floretAccent: "#171311",
      stamenCount: 42,
      stigmaLobes: 10,
      filamentColor: "#342b27",
      antherColor: "#171311",
      stigmaColor: "#9aa17b",
      pollenColor: "#d7a23d",
      edgeRuffle: 0.1,
      baseDarkening: 0.42,
      petalOutline: "fan",
      longitudinalCurve: 0.16,
      lateralCup: 0.55,
      calyxForm: "cupped",
      sepalLength: 0.88,
      leafShape: "lobed",
      leafSerration: 0.22,
      leafPairs: 2,
      stemHairiness: 0.7,
      stemEccentricity: 0.1,
      stemRibbing: 0.06,
    },
  },
  Lily: {
    label: "Lily",
    referenceViews: ["front", "center", "side", "habit", "side-stem"],
    traits: [
      "Six recurved tepals that open into a bright star",
      "Spotted petals with a visible pollen-heavy center",
      "Tall, upright flowers on a clean stem",
      "Long lance leaves, hanging stamens, and a clean stem junction",
    ],
    referenceChecks: [
      "Front should show six tepals with strong reflex on the outer edges.",
      "Center should carry long stamens with orange pollen.",
      "Spots and warmer tones should be visible on the petals.",
      "The stem view should remain clean and vertically elegant.",
      "The side-stem reference should keep the flower-to-stem transition slender.",
    ],
    store: {
      petalCount: 6,
      petalLength: 2.08,
      petalWidth: 0.62,
      petalCurl: 0.42,
      petalWaviness: 0.06,
      petalThickness: 0.7,
      petalFold: 0.16,
      petalTwist: 0.1,
      petalRuffle: 0.26,
      petalNotch: 0.02,
      petalVeinStrength: 0.82,
      petalBaseWidth: 0.88,
      petalAge: 0.04,
      petalSpots: 0.18,
      petalGuideStrength: 0.08,
      petalAsymmetry: 0.08,
      petalTranslucency: 0.18,
      petalEdgeWear: 0.03,
      petalSheen: 0.18,
      bloom: 0.88,
      variation: 0.1,
      petalColor: "#f0d891",
      petalTipColor: "#ea9f3e",
      centerColor: "#b46f21",
      stemColor: "#436f3e",
      backgroundColor: "#ffffff",
      centerDensity: 0.82,
      centerSize: 0.96,
      centerProfile: 0.96,
      centerFloretSize: 1.02,
      centerSpread: 0.82,
      centerStamenLength: 1.56,
      centerAntherSize: 1.18,
      centerStigmaSize: 1.04,
      sepalSize: 0.96,
      sepalSpread: 0.32,
      stemCurve: 0.1,
      stemHeight: 1.14,
      stemThickness: 0.82,
      stemTaper: 0.18,
      stemNodeCount: 4,
      stemHairDensity: 0.12,
      leafDensity: 1.08,
      leafLength: 1.16,
      leafWidth: 0.86,
      leafCurl: 0.1,
      leafSerration: 0.12,
      leafVeinDensity: 1.02,
      leafDroop: 0.1,
      leafAsymmetry: 0.05,
      leafAge: 0.04,
      bloomTilt: 0.06,
      bloomTurn: -0.04,
      lightIntensity: 1.3,
    },
    structure: {
      layers: [
        { count: 0.5, length: 1, width: 0.92, lift: -0.08, offset: 0 },
        { count: 0.5, length: 0.94, width: 0.86, lift: 0.12, offset: 0.5 },
      ],
      notch: 0,
      profile: 0.66,
      centerRadius: 0.16,
      florets: 24,
      sepals: 3,
      leafWidth: 0.4,
      centerHeight: 0.2,
      floretAccent: "#bd6d68",
      stamenCount: 6,
      stigmaLobes: 3,
      filamentColor: "#d7c6a1",
      antherColor: "#8d4a2b",
      stigmaColor: "#809044",
      pollenColor: "#c77a31",
      styleLength: 1.55,
      ovaryPosition: "superior",
      ovaryScale: 0.82,
      calyxForm: "reflexed",
      sepalLength: 0.95,
      edgeRuffle: 0.045,
      baseDarkening: 0.6,
      petalOutline: "lanceolate",
      longitudinalCurve: 0.12,
      lateralCup: 0.72,
      leafShape: "lance",
      leafSerration: 0.015,
      leafPairs: 3,
      stemHairiness: 0.12,
      stemEccentricity: 0.09,
      stemRibbing: 0.08,
    },
  },
  Sunflower: {
    label: "Sunflower",
    referenceViews: ["front", "bracts", "foliage", "habit", "stem"],
    traits: [
      "Broad ray petals around a dense dark disk",
      "Heavy, sun-following head with visible bracts",
      "Tall, hairy stem with large cordate leaves",
      "The stem must carry the weight of the head convincingly",
    ],
    referenceChecks: [
      "Front should keep the disk dark and central.",
      "Ray petals should be broad, open, and strongly radial.",
      "Bracts and leaf habit should support the heavy head.",
      "The flower should feel broad and shallow in profile.",
      "The stem should read coarse, hairy, and structurally loaded.",
    ],
    store: {
      petalCount: 22,
      petalLength: 1.58,
      petalWidth: 0.5,
      petalCurl: 0.08,
      petalWaviness: 0.05,
      petalThickness: 0.68,
      petalFold: 0.04,
      petalTwist: 0.02,
      petalRuffle: 0.14,
      petalNotch: 0.02,
      petalVeinStrength: 1.12,
      petalBaseWidth: 0.72,
      petalAge: 0.03,
      petalSpots: 0,
      petalGuideStrength: 0.12,
      petalAsymmetry: 0.04,
      petalTranslucency: 0.12,
      petalEdgeWear: 0.03,
      petalSheen: 0.18,
      bloom: 0.94,
      variation: 0.14,
      petalColor: "#e6aa1d",
      petalTipColor: "#f6d45a",
      centerColor: "#3f2817",
      stemColor: "#406437",
      backgroundColor: "#ffffff",
      centerDensity: 1.18,
      centerSize: 1.12,
      centerProfile: 1.02,
      centerFloretSize: 1,
      centerSpread: 0.9,
      centerStamenLength: 0.9,
      centerAntherSize: 0.98,
      centerStigmaSize: 0.82,
      sepalSize: 1.12,
      sepalSpread: 0.54,
      stemCurve: 0.04,
      stemHeight: 1.18,
      stemThickness: 1.28,
      stemTaper: 0.16,
      stemNodeCount: 4,
      stemHairDensity: 1.72,
      leafDensity: 1.16,
      leafLength: 1.22,
      leafWidth: 1.18,
      leafCurl: 0.08,
      leafSerration: 0.1,
      leafVeinDensity: 1.24,
      leafDroop: 0.08,
      leafAsymmetry: 0.06,
      leafAge: 0.04,
      bloomTilt: -0.1,
      bloomTurn: 0.02,
      lightIntensity: 1.38,
    },
    structure: {
      layers: [
        {
          count: 1,
          length: 1,
          width: 0.88,
          lift: -0.04,
          offset: 0,
          role: "ray",
        },
        {
          count: 0.82,
          length: 0.88,
          width: 0.82,
          lift: 0.07,
          offset: 0.5,
          role: "ray",
        },
      ],
      notch: 0.025,
      profile: 0.8,
      centerRadius: 0.62,
      florets: 360,
      sepals: 14,
      leafWidth: 0.5,
      centerHeight: 0.28,
      floretAccent: "#d89a2b",
      stamenCount: 40,
      stigmaLobes: 5,
      filamentColor: "#a66525",
      antherColor: "#3d281b",
      stigmaColor: "#6f4825",
      pollenColor: "#e0a832",
      styleLength: 0.52,
      ovaryPosition: "inferior",
      ovaryScale: 1.08,
      calyxForm: "bracted",
      sepalLength: 1.28,
      edgeRuffle: 0.035,
      baseDarkening: 0.7,
      petalOutline: "lanceolate",
      longitudinalCurve: -0.08,
      lateralCup: 0.62,
      centerArchitecture: "composite",
      diskInnerColor: "#7d4b21",
      diskOuterColor: "#24170f",
      leafShape: "cordate",
      leafSerration: 0.1,
      leafPairs: 2,
      stemHairiness: 1.5,
      stemEccentricity: 0.15,
      stemRibbing: 0.14,
    },
  },
  Orchid: {
    label: "Orchid",
    referenceViews: ["front", "center", "labellum", "habit", "flowering-stem"],
    traits: [
      "Bilateral flower with a dominant labellum",
      "White petals and sepals with a pink-yellow throat",
      "Distinct column and compact reproductive axis",
      "An arching flowering stem with spaced blooms instead of a single head",
    ],
    referenceChecks: [
      "Front view should show a white, open phalaenopsis face.",
      "The lip should read as the visual anchor of the flower.",
      "The column should remain visible at the center.",
      "The bloom should feel asymmetric, not rotationally radial.",
      "The flowering stem should arc and carry multiple nodes.",
    ],
    store: {
      petalCount: 5,
      petalLength: 1.66,
      petalWidth: 0.84,
      petalCurl: 0.26,
      petalWaviness: 0.04,
      petalThickness: 0.68,
      petalFold: 0.16,
      petalTwist: 0.04,
      petalRuffle: 0.2,
      petalNotch: 0.08,
      petalVeinStrength: 0.7,
      petalBaseWidth: 0.92,
      petalAge: 0.04,
      petalSpots: 0.06,
      petalGuideStrength: 0.22,
      petalAsymmetry: 0.24,
      petalTranslucency: 0.22,
      petalEdgeWear: 0.02,
      petalSheen: 0.32,
      bloom: 0.8,
      variation: 0.08,
      petalColor: "#f5f2ef",
      petalTipColor: "#d9b7c2",
      centerColor: "#d8ad4a",
      stemColor: "#49704d",
      backgroundColor: "#ffffff",
      centerDensity: 0.78,
      centerSize: 0.88,
      centerProfile: 0.74,
      centerFloretSize: 0.88,
      centerSpread: 0.72,
      centerStamenLength: 0.8,
      centerAntherSize: 0.92,
      centerStigmaSize: 1.08,
      sepalSize: 0.88,
      sepalSpread: 0.18,
      stemCurve: 0.26,
      stemHeight: 1.18,
      stemThickness: 0.72,
      stemTaper: 0.22,
      stemNodeCount: 4,
      stemHairDensity: 0.04,
      leafDensity: 0.92,
      leafLength: 1.06,
      leafWidth: 0.78,
      leafCurl: 0.06,
      leafSerration: 0,
      leafVeinDensity: 0.82,
      leafDroop: 0.1,
      leafAsymmetry: 0.04,
      leafAge: 0.02,
      bloomTilt: 0.04,
      bloomTurn: -0.12,
      lightIntensity: 1.18,
    },
    structure: {
      layers: [
        {
          count: 0.6,
          length: 1,
          width: 0.78,
          lift: 0.02,
          offset: 0,
          role: "sepal",
          outline: "lanceolate",
          lateralCup: 0.68,
        },
        {
          count: 0.4,
          length: 0.86,
          width: 1.18,
          lift: 0.12,
          offset: 0.5,
          role: "petal",
          outline: "spatulate",
        },
        {
          count: 0.2,
          length: 0.58,
          width: 1.45,
          lift: -0.22,
          offset: 0,
          role: "lip",
          outline: "fan",
          lateralCup: 1.3,
          longitudinalCurve: -0.24,
          accentColor: "#a94a91",
          accentStrength: 0.68,
        },
      ],
      notch: 0.1,
      profile: 0.5,
      centerRadius: 0.2,
      florets: 16,
      sepals: 3,
      leafWidth: 0.72,
      centerHeight: 0.24,
      floretAccent: "#be6b9f",
      stamenCount: 2,
      stigmaLobes: 3,
      filamentColor: "#eee0cf",
      antherColor: "#d59b52",
      stigmaColor: "#a6538e",
      pollenColor: "#edc56d",
      styleLength: 0.62,
      ovaryPosition: "inferior",
      ovaryScale: 0.68,
      calyxForm: "reflexed",
      sepalLength: 0.78,
      edgeRuffle: 0.075,
      baseDarkening: 0.7,
      petalOutline: "spatulate",
      longitudinalCurve: 0.18,
      lateralCup: 0.95,
      petalArrangement: "bilateral",
      centerArchitecture: "column",
      inflorescenceArchitecture: "spike",
      inflorescenceCount: 5,
      inflorescenceSpacing: 0.44,
      inflorescenceSpread: 0.26,
      leafShape: "linear",
      leafSerration: 0,
      leafPairs: 1,
      stemHairiness: 0.05,
      stemEccentricity: 0.06,
      stemRibbing: 0.04,
    },
  },
  Lotus: {
    label: "Lotus",
    referenceViews: ["front", "side", "foliage", "fruit", "plant"],
    traits: [
      "Layered sculptural petals with a soft cup",
      "Raised seedpod center and broad floating foliage",
      "Pale pink-to-white petals with dew and sheen",
      "Full plant context keeps the floating architecture believable",
    ],
    referenceChecks: [
      "Front view should show a layered, almost circular lotus face.",
      "The center needs a yellow seedpod read, not a flat disk.",
      "Petals should fade from white to pink at the tips.",
      "The foliage reference should feel broad and aquatic.",
      "The plant shot should support an elevated bloom above the waterline.",
    ],
    store: {
      petalCount: 18,
      petalLength: 1.72,
      petalWidth: 0.78,
      petalCurl: 0.28,
      petalWaviness: 0.05,
      petalThickness: 0.76,
      petalFold: 0.18,
      petalTwist: 0.08,
      petalRuffle: 0.22,
      petalNotch: 0.02,
      petalVeinStrength: 0.86,
      petalBaseWidth: 1,
      petalAge: 0.02,
      petalSpots: 0,
      petalGuideStrength: 0.04,
      petalAsymmetry: 0.04,
      petalTranslucency: 0.24,
      petalEdgeWear: 0.04,
      petalSheen: 0.34,
      bloom: 0.72,
      variation: 0.08,
      petalColor: "#f2e1da",
      petalTipColor: "#d8a0ac",
      centerColor: "#d1a945",
      stemColor: "#4d745d",
      backgroundColor: "#ffffff",
      centerDensity: 1.04,
      centerSize: 0.9,
      centerProfile: 1.02,
      centerFloretSize: 0.96,
      centerSpread: 0.94,
      centerStamenLength: 1.14,
      centerAntherSize: 0.96,
      centerStigmaSize: 1,
      sepalSize: 1.1,
      sepalSpread: 0.18,
      stemCurve: 0.04,
      stemHeight: 1.06,
      stemThickness: 0.82,
      stemTaper: 0.14,
      stemNodeCount: 1,
      stemHairDensity: 0.06,
      leafDensity: 0.82,
      leafLength: 1.24,
      leafWidth: 1.26,
      leafCurl: 0.04,
      leafSerration: 0,
      leafVeinDensity: 0.96,
      leafDroop: 0.02,
      leafAsymmetry: 0.04,
      leafAge: 0.02,
      bloomTilt: 0.02,
      bloomTurn: 0.04,
      lightIntensity: 1.2,
    },
    structure: {
      layers: [
        { count: 1, length: 1, width: 1, lift: 0.08, offset: 0 },
        { count: 0.75, length: 0.8, width: 0.9, lift: 0.3, offset: 0.5 },
        { count: 0.5, length: 0.61, width: 0.8, lift: 0.47, offset: 0 },
      ],
      notch: 0,
      profile: 0.74,
      centerRadius: 0.34,
      florets: 110,
      sepals: 5,
      leafWidth: 0.58,
      centerHeight: 0.32,
      floretAccent: "#f2cf66",
      stamenCount: 34,
      stigmaLobes: 8,
      filamentColor: "#e7bd4d",
      antherColor: "#9f712a",
      stigmaColor: "#d1a943",
      edgeRuffle: 0.018,
      baseDarkening: 0.86,
      petalOutline: "lanceolate",
      longitudinalCurve: 0.28,
      lateralCup: 1.2,
      receptacleRadius: 0.14,
      innerCompression: 0.48,
      overlapJitter: 0.22,
      calyxForm: "cupped",
      sepalLength: 0.88,
      leafShape: "cordate",
      leafSerration: 0,
      leafPairs: 1,
      stemHairiness: 0.05,
      stemEccentricity: 0.08,
      stemRibbing: 0.06,
      centerArchitecture: "seedpod",
      ovaryPosition: "superior",
      ovaryScale: 0.96,
      pollenColor: "#c7a33b",
    },
  },
};

export function getHeroFlowerProfile(preset: FlowerPreset) {
  return preset in heroFlowerProfiles
    ? heroFlowerProfiles[preset as HeroFlowerPreset]
    : undefined;
}
